# Netlify 배포 설정 - 프론트엔드

[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# SPA 라우팅을 위한 리다이렉트 설정
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 환경 변수는 Netlify Dashboard에서 설정
# VITE_SUPABASE_URL
# VITE_SUPABASE_ANON_KEY
# VITE_API_BASE_URL
