services:
  # 백엔드 API 서버 (Render)
  # 프론트엔드는 Netlify에 배포됨
  - type: web
    name: dockdock-api
    env: node
    region: singapore
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: ALADIN_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /health
